name: spellcheck-woke
'on':
  push: null
  workflow_dispatch: null
jobs:
  woke:
    name: Run woke
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: woke
      uses: get-woke/woke-action@v0
      with:
        fail-on-error: true
  spellcheck:
    name: Run spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Spellcheck
      uses: rojopolis/spellcheck-github-actions@0.29.0
